name: Docker Image CI

on:
  push:
    branches: ["main", "sandbox", "production", "nameFixes"]

env:
  DEP_IMAGE: beckn-gateway-dep
  IMAGE_NAME: beckn-gateway
  DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
  # VERSION: ${{git rev-parse --short ${{github.sha}} }}
  DEP_LABEL: ${{github.ref_name}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: set up env var
        run: echo "VERSION=$(git rev-parse --short "$GITHUB_SHA")"
      - name: use env var
        run: echo ${{ env.VERSION }}
      # - name: Build the DockerDep image
      #   run: docker build -t $DOCKER_USER/$DEP_IMAGE:$DEP_LABEL -f Dockerfile.dep .
      # - name: DockerDep Push
      #   run: docker push $DOCKER_USER/$DEP_IMAGE:$DEP_LABEL
      - name: Build the Docker image
        run: docker build -t $DOCKER_USER/$IMAGE_NAME:${{env.VERSION}} -f Dockerfile --build-arg "DEP_LABEL=$DEP_LABEL" --build-arg "DEP_IMAGE_PATH=$DOCKER_USER/$DEP_IMAGE" .
      - name: Docker Push
        run: docker push $DOCKER_USER/$IMAGE_NAME:${{env.VERSION}}
