name: Docker Image CI

on:
  push:
    branches: ["main", "sandbox", "production", "name/fixes"]

env:
  DEP_IMAGE: beckn-gateway-dep
  IMAGE_NAME: beckn-gateway
  DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker login
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the DockerDep image
        run: docker build -t $DOCKER_USER/$DEP_IMAGE:latest -f Dockerfile.dep .
      - name: DockerDep Push
        run: docker push $DOCKER_USER/$DEP_IMAGE:latest
      - name: Build the Docker image
        run: docker build -t $DOCKER_USER/$IMAGE_NAME:latest -f Dockerfile --build-arg "DEP_LABEL=latest" --build-arg "DEP_IMAGE_PATH=$DOCKER_USER/$DEP_IMAGE" .
      - name: Docker Push
        run: docker push $DOCKER_USER/$IMAGE_NAME:latest
